import fs from 'node:fs/promises';
import {catalog} from '../js/library/catalog.js';
// This is a scaffold for missing pages. Existing HTML and artwork are the
// editable source of truth and must never be overwritten by regeneration.
async function writeIfMissing(file, contents) {
  try { await fs.writeFile(file, contents, {flag: 'wx'}); }
  catch (error) { if (error.code !== 'EEXIST') throw error; }
}
const scroll=(content)=>`<div class="fx-scroller" data-scroller tabindex="0" role="region" aria-label="可捲動展示區">${content}</div>`;
const status=`<span class="fx-render-status" data-render-status>正在建立畫面…</span>`;
const headings=['ART DIRECTION','WEB DESIGN','WEB DEVELOPMENT','GRAPHIC DESIGN','MOVIE DIRECTION'];
const media=(i)=>`<div class="fx-service-video" data-art="${i}"><video src="../../assets/motion-study.webm" muted loop playsinline preload="metadata" aria-label="自製幾何短片 ${i+1}"></video><span class="fx-caption">STUDY / 0${i+1}</span></div>`;
const pageView=(b=false)=>`<div data-page-view class="${b?'fx-page-b':'fx-page-a'}"><span class="fx-caption">${b?'02 / 作品展示':'01 / 索引展示'}</span><div class="fx-page-orb" aria-hidden="true"></div><h2>${b?'a new<br>perspective.':'between<br>two pages.'}</h2><p>${b?'新的構圖、新的頁面。返回時仍保留瀏覽歷史。':'點擊連結，舊畫面淡出後，新畫面接續淡入。'}</p><a href="${b?'index.html':'page-b.html'}" data-route>${b?'← 回到索引':'前往作品頁 →'}</a></div>`;
const templates={
 'blink-type':scroll(`<div class="fx-type-copy"><div class="fx-wordmark" data-blink>form.</div><h2 data-blink>eloquent<br>silence.</h2><p data-blink>在細微的變化裡，\n找到新的觀看方式。</p><p class="fx-caption" data-blink>SCROLL TO MEET THE TEAM ↓</p></div>${['視覺探索 / Visual','互動實驗 / Interactive','動態研究 / Motion'].map((t,i)=>`<div class="fx-member"><span data-blink data-row="${i}">${t}</span><span data-blink data-row="${i}">STUDIO ${String(i+1).padStart(2,'0')}</span></div>`).join('')}<div class="fx-type-end"></div>`),
 'chaos-attractor':`<canvas aria-hidden="true"></canvas>${scroll(`<div class="fx-field-part"><h2>A field<br>of possibilities.</h2><p>捲動跨過下方分界，粒子會變成另一個形態。</p></div><div class="fx-boundary">ABOUT / 形態切換分界</div><div class="fx-field-part"><h2>Another<br>point of view.</h2><p>反向捲回即可恢復第一組流形。</p></div>`)}<button class="fx-action fx-top-action" data-morph>切換形態</button>${status}`,
 'orbit-cubes':`<h2>WORKS</h2><div class="fx-orbit" data-orbit></div><p>3 個尺度。各自自轉。<br>共享一個緩慢公轉的空間。</p>`,
 'unfold-cube':`${scroll(`<div class="fx-unfold-space">慢慢往下捲動。<br>方塊跨過中線時，依序擺正與攤平。</div><div class="fx-net-anchor" data-net></div><div class="fx-unfold-end">回捲時保留展開狀態。<br>可用上方按鈕手動收合。</div>`)}<div class="fx-threshold"><span>TRIGGER / 50%</span></div><button class="fx-action fx-top-action" data-unfold>展開 / 收合</button>`,
 'lattice-pulse':`<canvas aria-hidden="true"></canvas><h2>A QUIETER WORLD.<br>A DIFFERENT PERSPECTIVE.</h2><button class="fx-action fx-top-action" data-expand>切換密度</button>${status}`,
 'pixel-stretch':`<canvas aria-hidden="true"></canvas><span class="fx-stretch-label">HOVER TO REVEAL / 移入圖片</span>`,
 'service-slider':`<div class="fx-service-layout"><div><div class="fx-media-window" data-media><div class="fx-media-track" data-track>${headings.map((_,i)=>media(i)).join('')}</div></div></div><div>${headings.map((h,i)=>`<section class="fx-service-row"><button data-service aria-expanded="${i===0}" aria-controls="service-panel-${i}"><span>0${i+1}.</span>${h}</button><div class="fx-service-panel" id="service-panel-${i}" data-panel data-open="${i===0}"><div><p>${['從畫面、構圖與文字出發，觀察形體的每個面向。','讓資訊與操作，自然形成清晰的瀏覽節奏。','將構想化為可操作、可調整的互動細節。','嘗試平面、色彩與材質之間的不同組合。','以連續影格，留下一段可以反覆觀看的時間。'][i]}</p></div></div></section>`).join('')}</div></div>`,
 'topics-accordion':`<h2>Topics</h2><div class="fx-topic-row"><button data-topic aria-expanded="false" aria-controls="topic-panel"><small>STUDY / 01</small><span>關於細微動作的觀察紀錄</span><i aria-hidden="true">↓</i></button><div class="fx-topic-panel" id="topic-panel" data-topic-panel data-open="false"><div><p>形體逐步展開，文字慢慢顯現。這是一則為展示高度動畫而撰寫的短文，點擊標題即可再次收合。</p><div class="fx-topic-art" role="img" aria-label="自製斜紋幾何圖形"></div></div></div></div>`,
 'mobile-menu':`<div class="fx-menu-header"><span class="fx-menu-mark">form.</span><button class="fx-menu-toggle" data-menu-open aria-label="開啟導覽選單" aria-haspopup="dialog" aria-expanded="false"><span></span><span></span></button></div><p class="fx-menu-title" data-menu-current>Explore<br>the quiet.</p><dialog class="fx-menu-dialog" aria-label="展示導覽"><div class="fx-menu-header"><span class="fx-menu-mark">form.</span><button class="fx-menu-toggle" data-menu-close aria-label="關閉導覽選單"><span></span><span></span></button></div><nav aria-label="展示頁面">${[['HOME','首頁'],['WORKS','作品'],['ABOUT US','關於'],['CONTACT','聯絡']].map(([t,c])=>`<a href="#${t.toLowerCase().replaceAll(' ','-')}" data-menu-page="${c}"><span data-menu-text>${t}</span></a>`).join('')}</nav><p data-menu-text>獨立動態研究<br>FORM / MOTION STUDIES<br>觀察細節，探索可能。</p></dialog>`,
 'link-feedback':`<a href="#demo" class="fx-link" data-local-link>WORKS / 左側進入<span></span></a><a href="#demo" class="fx-link fx-link--right" data-local-link>ABOUT / 右側進入<span></span></a><a href="#demo" class="fx-link fx-link--double" data-local-link>VIEW ALL STUDIES <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true" focusable="false"><path d="M6 18 18 6M6 6h12v12"/></svg><span></span><span></span></a><a href="#demo" class="fx-link fx-link--double" data-local-link>Visit Site <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true" focusable="false"><path d="M6 18 18 6M6 6h12v12"/></svg><span></span><span></span></a><div class="fx-scroll-hint">SCROLL <span class="fx-scroll-arrow" aria-hidden="true">⌄</span></div><p role="status" data-feedback>移入連結，觀察底線方向。</p>`,
 'page-transition':`${pageView()}<div class="fx-route-status" data-route-status aria-live="polite">目前頁面：index.html</div>`,
 'scroll-navigation':scroll(`<div data-scroll-content class="fx-scroll-content"><div class="fx-scroll-header" data-scroll-header><span>form.</span><span>SCROLL / EXPLORE</span></div><div class="fx-scroll-layout"><nav class="fx-scroll-nav" aria-label="展示內容目錄">${['Outline','Graphic','Team'].map((s,i)=>`<button data-jump="${i}" aria-current="${i===0?'location':'false'}">${s}</button>`).join('')}</nav><div>${['the outline.','a darker<br>perspective.','a shared<br>direction.'].map((s,i)=>`<section data-section><span class="fx-caption">0${i+1} / ${['OUTLINE','GRAPHIC','TEAM'][i]}</span><h2>${s}</h2><p>慢速或快速捲動，左側目錄將跟隨目前的段落。點擊其他目錄可以前往指定位置，再向上捲動確認反向更新。</p><div class="fx-scroll-art" aria-hidden="true"></div></section>`).join('')}</div></div><div class="fx-scroll-status" data-scroll-status>正在準備捲動…</div></div>`),
 'video-reveal':`<h2>A moment in motion.</h2><div class="fx-video-window"><video src="../../assets/motion-study.webm" controls playsinline muted preload="metadata" aria-label="自製幾何形體短片"></video><div class="fx-video-cover" data-cover data-art="2"></div><button class="fx-video-play" data-play aria-label="播放展示影片"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false"><path d="m8 5 11 7-11 7Z"/></svg></button></div><p class="fx-video-caption" data-video-status role="status">自製短片 / 點擊封面開始播放</p>`,
 'contact-controls':`<h2>CONTACT</h2><form><fieldset><legend>想探索的方向（可複選）</legend><div class="fx-checks">${['網站設計','平面設計','互動開發','其他'].map((t,i)=>`<label class="fx-check-label"><input type="checkbox" name="category" value="${i}">${t}</label>`).join('')}</div></fieldset><label class="fx-field">名稱 *<input name="name" required autocomplete="off" placeholder="輸入展示用名稱"></label><label class="fx-field">Email *<input name="email" type="email" required autocomplete="off" placeholder="例如 demo@example.com"></label><label class="fx-field">內容 *<textarea name="message" required placeholder="輸入展示用內容"></textarea></label><button type="submit">檢查欄位 →</button><p role="status" data-form-status></p></form>`,
 'works-gallery':`<h2>WORKS</h2><div class="fx-gallery-filters" role="group" aria-label="作品分類">${[['all','全部'],['visual','視覺'],['motion','動態'],['type','字體']].map(([v,t])=>`<button data-filter="${v}" aria-pressed="${v==='all'}"><span>${t}</span></button>`).join('')}</div><div class="fx-gallery-grid">${['Still / 靜','Echo / 回響','Forms / 形','Field / 場','Trace / 痕','Orbit / 軌道'].map((title,i)=>`<article data-card data-category="${['visual','motion','type'][i%3]}"><h3>${title}</h3><p>${['VISUAL','MOTION','TYPE'][i%3]} / ORIGINAL STUDY</p><a href="../page-transition/page-b.html" aria-label="開啟 ${title}"><div class="fx-pixel-stretch" data-image><canvas aria-hidden="true"></canvas></div></a></article>`).join('')}</div>`,
 'home-sequence':`<div class="fx-chaos-attractor" data-combo-field><canvas aria-hidden="true"></canvas>${status}</div>${scroll(`<div class="fx-combo-header">FORM / MOTION STUDIES</div><section class="fx-combo-part"><span class="fx-combo-logo" data-blink>form.</span><h2 data-blink>less noise.<br>more feeling.</h2><p data-blink>向下捲動，觀察不同效果如何共享同一段動態關係。</p></section><section class="fx-orbit-cubes" data-combo-cubes><h2>WORKS</h2><div class="fx-orbit" data-orbit></div></section><section class="fx-combo-category" data-combo-category><h2>art direction</h2><p>立方體在進入畫面後，攤平為影像組合。</p><div class="fx-unfold-cube" data-combo-unfold><div class="fx-net-anchor" data-net></div></div></section><section class="fx-combo-part" data-combo-about><h2 data-blink>eloquent<br>silence.</h2><p>跨過 About 分界時，背景粒子轉換到另一組流形。往回捲動，形態便隨之復原。</p></section>`)}`
};
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function shell(item,b=false){const html=b?`${pageView(true)}<div class="fx-route-status" data-route-status>目前頁面：page-b.html</div>`:templates[item.slug];return `<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0a0a0a"><title>${item.name}${b?' / 作品頁':''} — 形體 / 感知</title><link rel="icon" href="../../assets/favicon.svg"><link rel="stylesheet" href="../../css/demo.css"><link rel="stylesheet" href="effect.css"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@400;500&display=swap" rel="stylesheet"></head>
<body data-demo="${item.slug}"><div class="lib-wrap"><header class="lib-header"><a class="lib-brand" href="../../library.html">形體 <span>/</span> 特效庫</a><nav><a href="../../audit.html">觀察紀錄</a><a href="../../index.html">既有創作</a></nav></header><main><div class="demo-head"><div><a class="demo-back" href="../../library.html">← 全部效果</a><p class="lib-kicker">${item.id} / ${item.category}</p><h1>${item.name}</h1><p>${item.summary}</p></div><span class="demo-status" data-validation>實作完成 · 驗證紀錄載入中</span></div><div class="demo-workbench"><div class="demo-preview"><div class="demo-stage"><section class="fx-${item.slug}" data-effect-root aria-label="${item.name}展示">${html}</section></div><div class="demo-toolbar"><button class="lib-button lib-button--accent" data-replay>重播 ↻</button><button class="lib-button" data-reset>重設</button><button class="lib-button" data-pause aria-pressed="false">暫停</button><p>${item.hint}</p></div></div><aside class="demo-controls" aria-label="參數控制"><h2>參數調整</h2><div data-control-list></div><p class="demo-mode" data-mode></p></aside></div><section class="demo-info" data-info aria-label="技術資訊與移植範例"></section></main><footer class="lib-footer"><span>${item.id} / ORIGINAL MOTION STUDY</span><a href="../../library.html">回到特效庫 ↑</a></footer></div><noscript>請啟用 JavaScript，才能操作效果與參數。</noscript><script type="module" src="../../js/library/demo.js"></script></body></html>`;}
await fs.mkdir('assets/previews',{recursive:true});
for(const item of catalog){await fs.mkdir(`demos/${item.slug}`,{recursive:true});await writeIfMissing(`demos/${item.slug}/index.html`,shell(item));if(item.slug==='page-transition')await writeIfMissing(`demos/${item.slug}/page-b.html`,shell(item,true));
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 400"><rect width="640" height="400" fill="#252e24"/><g stroke="#a9bd85" fill="none" stroke-width="2">${Array.from({length:18},(_,i)=>`<ellipse cx="360" cy="195" rx="${60+i*10}" ry="${30+i*7}" transform="rotate(${i*4} 360 195)"/>`).join('')}</g><text x="32" y="48" fill="#e6f3cc" font-size="18" font-family="monospace">${item.id} / MOTION STUDY</text></svg>`;await writeIfMissing(`assets/previews/${item.slug}.svg`,svg);
}
await writeIfMissing('library.html',`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="從 NIRNOR 實際觀察的動畫與互動出發，探索可操作、可移植的原生 JavaScript 特效庫。"><title>形體 / 特效庫 — NIRNOR 動態研究</title><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="css/library.css"></head><body><div class="lib-wrap"><header class="lib-header"><a class="lib-brand" href="library.html">形體 <span>/</span> 特效庫</a><nav><a href="audit.html">觀察紀錄</a><a href="index.html">既有創作 <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true" focusable="false"><path d="M6 18 18 6M6 6h12v12"/></svg></a></nav></header><main><section class="lib-hero"><div><p class="lib-kicker">NIRNOR / MOTION STUDIES</p><h1>拆解動態，<br><em>看見細節。</em></h1></div><aside><p>從真實操作與公開程式碼出發，將 NIRNOR 的動態語言整理為獨立、可調整的互動實驗。</p><p>每個效果都附來源證據、實際使用技術與移植範例。</p><div class="lib-stats"><div><strong>14</strong><span>獨立效果</span></div><div><strong>02</strong><span>組合展示</span></div><div><strong>ESM</strong><span>原生模組</span></div></div></aside></section><section class="lib-tools" aria-label="搜尋與篩選"><div class="lib-search-row"><label>尋找效果<input type="search" id="effect-search" placeholder="搜尋名稱、觸發方式或技術…" autocomplete="off"></label><label>實際使用套件<select id="package-filter"><option value="">全部套件</option><option>無額外動畫套件</option><option>Three.js 0.170.0</option><option>Lenis 1.3.21</option></select></label><label>API 與技術<select id="tech-filter"><option value="">全部技術</option></select></label></div><div class="lib-categories" id="category-filter" role="group" aria-label="效果分類"></div></section><div class="lib-result"><span id="result-count" role="status"></span><a href="audit.html">查看原站效果對照 →</a></div><div class="lib-grid" id="effect-grid"></div><p class="lib-empty" id="empty-state" hidden>找不到相符效果，請調整搜尋或篩選條件。</p><section class="lib-existing"><div><p class="lib-kicker">EXISTING EXPLORATIONS</p><p>原有的鍍鉻雕塑、粒子星雲與流動地景仍完整保留。這些屬於獨立概念創作，不作為原站效果的技術證據。</p></div><a class="lib-button" href="index.html">探索既有創作 <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true" focusable="false"><path d="M6 18 18 6M6 6h12v12"/></svg></a></section></main><footer class="lib-footer"><span>形體 / 感知 — 獨立動態研究，非 NIRNOR 官方網站</span><a href="https://nirnor.jp/" target="_blank" rel="noopener noreferrer">來源 NIRNOR <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true" focusable="false"><path d="M6 18 18 6M6 6h12v12"/></svg></a></footer></div><script type="module" src="js/library/browse.js"></script></body></html>`);
await writeIfMissing('audit.html',`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>原站觀察與效果對照 — 形體 / 特效庫</title><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="css/library.css"></head><body><div class="lib-wrap"><header class="lib-header"><a class="lib-brand" href="library.html">形體 <span>/</span> 特效庫</a><nav><a href="library.html">全部效果</a></nav></header><main class="lib-audit"><p class="lib-kicker">OBSERVATION / EVIDENCE</p><h1>觀察與實作對照</h1><p>本次記錄以實際開啟的 NIRNOR 公開頁面、DOM、CSS、JavaScript 與 Chrome 操作為依據。原站可確認 Three.js r182、Lenis 1.3.21、React 與 TanStack Router；本特效庫採原生 HTML、SCSS 與 ES Modules。</p><p><a href="docs/OBSERVATIONS.md">完整操作紀錄</a> · <a href="docs/VALIDATION.md">本機驗證報告</a> · <a href="README.md">啟動及移植說明</a></p><h2>走查範圍</h2><ul><li>首頁：首次載入、完成、重新整理，慢速 / 快速 / 反向捲動，5 個分類立方體、About、服務切換、點陣宣言與消息展開。</li><li>Works：分類切換、圖片 hover 重播、點擊詳情與瀏覽器返回。</li><li>詳情：ReoNa Calendar 2022、SumireHanaTen、YanagiharaYoichiroSaiseiJinta、acidandroid2010-2018。</li><li>Contact：欄位與控制項；未向原站送出資料。</li><li>桌面 1440 × 1000、手機 390 × 844、平板 768 × 1024 與 resize；觸控與 reduced-motion 的本機實測另見報告。</li></ul><h2>原站技術確認</h2><ul><li>已確認：Canvas 的 data-engine="three.js r182"；Lenis 版本值 1.3.21；自訂粒子 attributes / uniforms；圖片拉伸 shader；CSS blink、grid 高度、底線位移、View Transition。</li><li>推測：視覺採用的藝術方向與設計意圖；不作技術歸因。</li><li>未確認：原站未走查作品頁是否另有內容特例；外部影片完整播放及聯絡送出後狀態。</li><li>沒有觀察或找到足夠證據：GSAP、ScrollTrigger、游標磁吸、水平 pin、跑馬燈、noise shader、bloom。未替原站增加這些效果。</li></ul><h2>逐項對照</h2><div class="lib-table-wrap"><table><thead><tr><th>ID / demo</th><th>來源區塊 / 觸發</th><th>原站技術證據</th><th>實作 / 驗證</th></tr></thead><tbody>${catalog.map(item=>`<tr><td><a href="demos/${item.slug}/">${item.id}<br>${item.name}</a></td><td><a href="${item.source}" target="_blank" rel="noopener noreferrer">${item.block}</a><br>${item.trigger}</td><td>已確認<br>${item.evidence}</td><td data-status="${item.slug}">實作完成<br>驗證紀錄載入中</td></tr>`).join('')}</tbody></table></div><h2>已知限制</h2><p>內建瀏覽器工具因缺少 sandboxPolicy 無法連線，改以本機 Chrome + Playwright 完成走查。原站不是逐幀完全相同的複製：文字與素材均為自製，動畫時序按公開程式碼及操作觀察重建，視覺差異逐 demo 列出。未宣稱已分析所有 45 個作品頁。</p><p>原站新聞內文使用 dangerouslySetInnerHTML，僅靠客戶端公開程式碼无法確認後端是否淨化。若內容來源可被不可信任者修改，可能影響新聞瀏覽者；建議在可信任伺服端作允許清單 HTML 淨化。本 demo 全部使用固定文字與 textContent，未複製這項渲染方式。</p></main><footer class="lib-footer"><a href="library.html">回到特效庫</a><span>來源證據與 demo 技術分別標示</span></footer></div><script type="module" src="js/library/audit.js"></script></body></html>`);
await writeIfMissing('assets/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="#0a0a0a"/><text x="10" y="25" font-family="Georgia" font-style="italic" font-size="30" fill="#dcf99a">f</text></svg>');
console.log(`已檢查 ${catalog.length} 個獨立 demo、作品轉場第 2 頁、特效庫與對照頁；僅補建缺少的檔案。`);
